### ISSUE TITLE
Add a read me

### ISSUE THREAD

**Issue by mhanf** [mhanf/ShinyLemonPie#2]

**Comment by akhil888binoy** [comment]
can you please assign this to me?

**Comment by mhanf** [comment]
Hello Akhill thanks you very much  for your interest. this is unfortunatly a Early stage work in progress ... sorry i really want to finalize it before opening to external contributions.  Do you need the package  for a particulier project? Maybe i can develop in priority some functionnalities that you need ? Best regards
